### ISSUE TITLE
D3, mapping, and CA water

### ISSUE THREAD

**Issue by adynata** [hackbrightacademy/pt-frontend-fall-2015#10]
Hi all,
I am hoping to work on a project that utilizes D3, and either the https://www.openstreetmap.org API or google maps to produce something that uses information on drought or biodiversity.

I found this as a resource: http://oad.simmons.edu/oadwiki/Data_repositories

I'm particularly interested in working with data from this org: http://bwc.berkeley.edu/California/default.htm

Also I believe that there was someone in class who was wanting to work on a project related to the farm to table supply chain, and I have at least some ideas about that. I don't know if it's something I want to work on directly, but I'm really interested in talking through it. I've spent a lot of time in work that's adjacent, and have thought through how the information, on, say, how produce availability might be collected and communicated. 

Unrelated to the final project, I've been perusing the Deep Lab book that was published last year - it's not directly related to the coursework or the final project, but I'm really inspired by what this group is doing and I think it's worth sharing: http://studioforcreativeinquiry.org/publications/deep-lab-book

**Comment by kbryerman** [comment]
I really like this idea of tracking the drought/biodiversity, possibly incorporating how it impacts our food/farming in California. 

Interested on working on this and exploring these topics further.

**Comment by pineapplechiu** [comment]
Hi, I'm also interested in d3, mapping and data visualization! I can provide GIS and database support.
