### ISSUE TITLE
Code brunch and Uber share

### ISSUE THREAD

**Issue by LijieZhou** [hackbrightacademy/pt-frontend-fall-2015#11]
Hi everyone, 

We had a great time here at code brunch and solved several problems. While chatting with @SofyaMulenok @koreoliver@JamieCorley and @demiskipper, we realize it would be nice to see who are interested in sharing a Uber after class, which would be a safer, faster and less expensive. 

Follow the thread or talk in class tomorrow. :)

Lijie

**Comment by demiskipper** [comment]
I'm Lower Haight :)

**Comment by koreoliver** [comment]
I live in lower pacific heights:)
