### ISSUE TITLE
Group Project Wireframes

### ISSUE THREAD

**Issue by SoItGoes33** [hackbrightacademy/pt-frontend-fall-2015#14]
Hi -

Quick question: are the wireframes due Monday, 8/31 or Wednesday 9/2? For some reason, I keep thinking Monday even though the syllabus says that they're due on Wed.  Could someone just confirm for me which day it actually is?  Thanks, Susan

**Comment by carolc** [comment]
I believe it is due Wednesday!

**Comment by DiyahM** [comment]
Yes, Wednesday 9/2. Also, don't forget to set up some time with one of the instructors to verify that the scope of your project is within reason. It may be helpful to do this before you create wireframes.
