### ISSUE TITLE
General Homework Question

### ISSUE THREAD

**Issue by SoItGoes33** [hackbrightacademy/pt-frontend-fall-2015#15]
In regard to our own portfolio pages, can we keep updating them by discarding old homework requirements for this week's homework assignment? I ask this because last week's assignment was to incorporate a couple paragraph's of text, include the side nav bars, the footer, etc.  For the couple paragraphs of text, I just pulled in something from wikipedia and then styled it with css.  Can I just delete those paragraphs and then include this week's homework assignment in its place (I also want to delete some of the side nav bars).  Or is the idea of the homework meant to be cumulative and we should include all of the requirements from each of the homework assignments in our portfolio pages?

Thanks,
Susan

**Comment by DiyahM** [comment]
Hi @SoItGoes33,

Yes, please discard any old homework requirements if it does not work with the design or layout that you want for your final portfolio.
