### ISSUE TITLE
Sunday study group

### ISSUE THREAD

**Issue by JamieCorley** [hackbrightacademy/pt-frontend-fall-2015#17]
Hi all - Since we don't have an official coding brunch at school this weekend, would anyone be interested in meeting at a coffee shop on Sunday at noon for two hours or so to review concepts from the week and go over code exercises?  We can do pair programming and review solutions to all exercises from the previous week by explaining them to each other.  

Please reply to this issue if you're interested. 

Coding meetup
Sunday, Sept. 6
Noon - 2 PM 
Location - TBD but near school, probably

**Comment by soumiafares** [comment]
Count me in!! :)

**Comment by demiskipper** [comment]
Yuuup.

On Mon, Aug 31, 2015 at 9:18 PM, Soumia Fares <notifications@github.com>
wrote:

> Count me in!! :)
>
>
> > On Aug 31, 2015, at 9:17 PM, Jamie Corley <notifications@github.com>
> wrote:
> >
> > Hi all - Since we don't have an official coding brunch at school this
> weekend, would anyone be interested in meeting at a coffee shop on Sunday
> at noon for two hours or so to review concepts from the week and go over
> code exercises? We can do pair programming and review solutions to all
> exercises from the previous week by explaining them to each other.
> >
> > Please reply to this issue if you're interested.
> >
> > Coding meetup
> > Sunday, Sept. 6
> > Noon - 2 PM
> > Location - TBD but near school, probably
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackbrightacademy/pt-frontend-fall-2015/issues/17#issuecomment-136581234>
> .
>



-- 
*Demi Skipper*
Architect
Penney Design Group
Demiskipper@gmail.com

**Comment by SofyaMulenok** [comment]
I might join as well!

**Comment by koreoliver** [comment]
me too:)

**Comment by SoItGoes33** [comment]
Me me me also.

**Comment by JamieCorley** [comment]
We're going to meet at noon tomorrow (Sunday) at Cup A Joe coffee near school.  I called to make sure they offer Wi-Fi on weekends.  
Hope to see you all there! 

896 Sutter St
(between Jones St & Leavenworth St)
San Francisco, CA 94109
(415) 563-7745
http://cupajoecoffeehaus.com/
