### ISSUE TITLE
8/12 Class Notes -- Git, Blogging, Office Hours, Pairing

### ISSUE THREAD

**Issue by DiyahM** [hackbrightacademy/pt-frontend-fall-2015#4]
Love how everyone is starting to become familiar with Git and Github. Keep practicing and it will become even more familiar.

<b>Some More Notes on Git</b>
- <b>When to use 'Fork and Pull': </b> If you are already an collaborator on a project, you do not have to 'fork and pull'. Instead collaborators only have to pull down the repo (git clone <remote-gitl-url>) if its not already local. Then you can push directly to the repo. Fork and pull is used if you are not a collaborator, but would like your contributions to be added back to the main project. 
- <b>Branches:</b>We talked briefly (very briefly) about branching in class when we talked about the gh-pages branch. For this class, we will only be using the master and gh-pages branches. If you would like to know more details about branching, https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
- <b>Gitignore:</b> There are times when you do not want to add files to your repo. An example of this are files created by your operating system, such as '.DS_Store'. You can tell git to permanently ignore these files by putting them into a .gitignore file. Here are some instructions on creating a .gitignore. https://help.github.com/articles/ignoring-files/

<b>Blogging</b>
If you are blogging about your learning journey, please let us know. You can tweet me (hadiyahdotme on twitter), email me, or post your blog posts on this forum. 
- @katesteinmeyer wrote a recap of her first week. You can read it here http://www.katesteinmeyer.com/blog/2015/8/12/command-lines
- Also, one of the intro to programming students wrote about her first day at Hackbright. https://tiffanyhoodprice.wordpress.com/2015/08/11/first-day-of-class/

<b>Pairing</b>
Reminder, you will be switching pairing partners every week. So, be prepared to work with a new classmate on Monday.

<b>Office Hours</b>
All of the instructors are available to help outside of classroom hours.  We are primarily available 1 - 2 hours prior to class start. If you would like to meet with us for additional help, please email us to let us know you'll be coming in early. If those times do not work for you, still email us and we can work together to find a mutual convenient time.

**Comment by ellatronic** [comment]
How do I add little folders to my repos? For example, pt-frontend-fall-2015 has week1, week2, week3, and etc. folders, then inside are the resources for that particular week.

**Comment by DiyahM** [comment]
In your local working directory create the folder and add files to these folders. Then when you do a 'git status', they will show up as untracked. Then add, commit, and push to github.
