### ISSUE TITLE
Travel Itinerary Project

### ISSUE THREAD

**Issue by demiskipper** [hackbrightacademy/pt-frontend-fall-2015#5]
Hi! 

I am really interesting in the Travel Itinerary Project. I don't remember who brought it up, but would love to be on a team with whoever it was, as well as a third.

Demi

**Comment by nmrosendin** [comment]
I had one of the travel ideas, which was similar to I think Jamie's? My idea was around plotting itineraries on maps and being able to save, share, edit them with others. Happy to work with you @demiskipper !

**Comment by demiskipper** [comment]
Awesome! Itineraties/Travel/Maps project sound great, @nmrosendin.

**Comment by demiskipper** [comment]
We could also do 3, if you want @nmrosendin & @JamieCorley.

**Comment by JamieCorley** [comment]
Hey!  I had the idea to crowdsource curated travel itineraries. I really like the idea of plotting itineraries so users can save/share/edit.  I'm all for teaming up if you're interested @nmrosendin @demiskipper

**Comment by demiskipper** [comment]
Sounds good to me :)
The map could be really awesome for this to plot different colors for different categories (hotels, restaurants, activities to go to etc) as well as to be able to send someone your itinerary/map associated with it.

**Comment by JamieCorley** [comment]
Like that @demiskipper.  @nmrosendin - Is this [http://www.kayak.com/explore/] similar to what you were thinking, except instead of flight prices the flags would represent itineraries?

**Comment by demiskipper** [comment]
@nmrosendin @JamieCorley 
This is interesting too, using someone API to pull certain POIs (points of interest) on to a map.
https://www.mapbox.com/mapbox.js/example/v1.0.0/places-from-foursquare/

**Comment by nmrosendin** [comment]
@demiskipper @JamieCorley  sounds great!

**Comment by JamieCorley** [comment]
What if there was a way to also see other travellers on a map?  I guess that would require some sort of checkin component?  I'm envisioning a Tinder or Hinge-like feature on a Mobile App (which I know is beyond this course) but instead facilitating relationships, you swipe profiles of other people who are also visitors to the area and are looking for new buddies to hang with.  I bring this up because two of my friends just went on solo trips and mentioned it was difficult to meet people out. 

Just throwing some ideas out there.

**Comment by demiskipper** [comment]
ooh I definitely like that idea. Let's shoot for the stars here, and then we can reel it back if/when we need to.

**Comment by demiskipper** [comment]
You if you're going to the same places you could potentially share rooms, go to bars, etc

**Comment by JamieCorley** [comment]
Exactly!  Taking the hostel experience online.  And for the map, perhaps each location could have three categories of itineraries: Those planning a trip, those actually there/on location, and archived/old itineraries for reference. 

Buttons/pins: "I'm planning to go here"; "I'm here"; "I was there"

**Comment by demiskipper** [comment]
This actually is working out so well, I was the one who had mentioned I was interested in an air bnb type project.

**Comment by JamieCorley** [comment]
@demiskipper @nmrosendin Are you going to the coding brunch tomorrow (Sunday)?

**Comment by demiskipper** [comment]
Yep! I'm going to go towards the beginning

**Comment by nmrosendin** [comment]
Unfortunately I can't make it today, plan to be at the next one for sure!

**Comment by JamieCorley** [comment]
@demiskipper @nmrosendin  I think it would be helpful to get a few of our ideas fleshed out this week before we dive into the class project portion of the course.  We can brainstorm and organize our thoughts then choose which ones we want to execute.  I divided the sections into "Purpose," "Functionality" and "Design" but we can change these whenever.  See you on Wednesday! 

Purpose
Why do people visit this site?
- To gather information about an upcoming trip
- For travel inspiration 
- To build, edit their own itineraries 

Functionality
What should the site do
- Allow users to create, share, save and edit (collaborate?) travel itineraries  
- Plot itineraries onto a map so users can roll over a city and see different itineraries for that city 
- Show other travelers in a city 

Design
What should the site look like 
- I like minimalist design (Medium, Uber) but am not married to any particular design

**Comment by DiyahM** [comment]
Hey Guys! Thanks for being proactive about picking a project and team. As this team now has 3 members, I'm going to close this thread.

Next steps:
1) One of you should create a repo under your own account and add team members as a collaborators.
2) Continue the discussion in the new repo using issues.
