### ISSUE TITLE
Week 1 Consolidated HW Feedback and Demos

### ISSUE THREAD

**Issue by DiyahM** [hackbrightacademy/pt-frontend-fall-2015#8]
Congrats on your first homework assignment!

You should have received individual feedback from either myself or @LijieZhou.

But here's some general feedback worth sharing with the class.
1. **It is best practice to use css instead of tables for page layout.** Your HTML should be semantic and accessible for screen readers. Tables should be used mostly be used to display tabular data. Therefore the screen readers would be able to distinguish between content on your page and tabular data. Here's another article on css vs tables. http://vanseodesign.com/css/css-divs-vs-tables/   
2. **Use img attributes or css to determine img size.** Both height and width are available as attributes on the img tag. You can view all the attributes on the img tag here http://www.w3schools.com/tags/tag_img.asp. In addition, we can set an img size by using css.  
Example:
```
img {
  width: 100px;
}
```
Also,  **Good job on use of git and gitpages** A week is not a long time to master git, but many of you were able to push your assignments and use github to ask questions. The familiarity of git will only come with more practice. 

Demos For Today's Class (8/19):
@carolc @ellatronic @nmrosendin @SofyaMulenok - Please come prepared to talk about this week's assignment and how you completed it, and any remaining questions that you may have. Max of 2mins. The purpose of the demo or the assignment is not completeness or correctness. Just a review of steps taken, any problems encounters, and/or lessons learnt.

**Comment by demiskipper** [comment]
Hi Diyah,

I am trying to put an image on my webpage from a local folder.  My html
reads

<img src="/images/3-hex.pdf"
     alt="www.google.com"
     style="width:128px;height:128px;">

and my images folder has been pushed to my repo and is in the same root
directory as my index folder.

What am I doing wrong?
Thanks!

Demi

On Wed, Aug 19, 2015 at 12:02 PM, Hadiyah Mujhid <notifications@github.com>
wrote:

> Congrats on your first homework assignment!
>
> You should have received individual feedback from either myself or
> @LijieZhou <https://github.com/LijieZhou>.
>
> But here's some general feedback worth sharing with the class.
> 1. *It is best practice to use css instead of tables for page layout.*
> Your HTML should be semantic and accessible for screen readers. Tables
> should be used mostly be used to display tabular data. Therefore the screen
> readers would be able to distinguish between content on your page and
> tabular data. Here's another article on css vs tables.
> http://vanseodesign.com/css/css-divs-vs-tables/
>
> 2. *Use img attributes or css to determine img size.* Both height and
> width are available as attributes on the img tag. You can view all the
> attributes on the img tag here http://www.w3schools.com/tags/tag_img.asp.
> In addition, we can set an img size by using css.
>
> Example:
>
> img {
>   width: 100px;
> }
>
> Also, *Good job on use of git and gitpages* A week is not a long time to
> master git, but many of you were able to push your assignments and use
> github to ask questions. The familiarity of git will only come with more
> practice.
>
> Demos For Today's Class (8/19):
> @carolc <https://github.com/carolc> @ellatronic
> <https://github.com/ellatronic> @nmrosendin
> <https://github.com/nmrosendin> @SofyaMulenok
> <https://github.com/SofyaMulenok> - Please come prepared to talk about
> this week's assignment and how you completed it, and any remaining
> questions that you may have. Max of 2mins. The purpose of the demo or the
> assignment is not completeness or correctness. Just a review of steps
> taken, any problems encounters, and/or lessons learnt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackbrightacademy/pt-frontend-fall-2015/issues/8>.
>



-- 
*Demi Skipper*
Architect
Penney Design Group
Demiskipper@gmail.com

**Comment by DiyahM** [comment]
A couple of things
1. Pdfs cannot be used in the img src tag. The browser doesn't know how to display it.
2. Also don't forget yourself closing tag on the img. It should display <img ... />

Let me know if that works.

**Comment by demiskipper** [comment]
Thanks :)
It worked.

Also, it is best practice to keep pushing changes as I completely change
things on the website or to make another repo and push to that?

On Thu, Aug 20, 2015 at 8:28 AM, Hadiyah Mujhid <notifications@github.com>
wrote:

> A couple of things
> 1. Pdfs cannot be used in the img src tag. The browser doesn't know how to
> display it.
> 2. Also don't forget yourself closing tag on the img. It should display
> <img ... />
>
> Let me know if that works.
>
> > On Aug 20, 2015, at 7:52 AM, demiskipper <notifications@github.com>
> wrote:
> >
> > Hi Diyah,
> >
> > I am trying to put an image on my webpage from a local folder. My html
> > reads
> >
> > <img src="/images/3-hex.pdf"
> > alt="www.google.com"
> > style="width:128px;height:128px;">
> >
> > and my images folder has been pushed to my repo and is in the same root
> > directory as my index folder.
> >
> > What am I doing wrong?
> > Thanks!
> >
> > Demi
> >
> > On Wed, Aug 19, 2015 at 12:02 PM, Hadiyah Mujhid <
> notifications@github.com>
> > wrote:
> >
> > > Congrats on your first homework assignment!
> > >
> > > You should have received individual feedback from either myself or
> > > @LijieZhou <https://github.com/LijieZhou>.
> > >
> > > But here's some general feedback worth sharing with the class.
> > > 1. *It is best practice to use css instead of tables for page layout.*
> > > Your HTML should be semantic and accessible for screen readers. Tables
> > > should be used mostly be used to display tabular data. Therefore the
> screen
> > > readers would be able to distinguish between content on your page and
> > > tabular data. Here's another article on css vs tables.
> > > http://vanseodesign.com/css/css-divs-vs-tables/
> > >
> > > 2. *Use img attributes or css to determine img size.* Both height and
> > > width are available as attributes on the img tag. You can view all the
> > > attributes on the img tag here
> http://www.w3schools.com/tags/tag_img.asp.
> > > In addition, we can set an img size by using css.
> > >
> > > Example:
> > >
> > > img {
> > > width: 100px;
> > > }
> > >
> > > Also, *Good job on use of git and gitpages* A week is not a long time
> to
> > > master git, but many of you were able to push your assignments and use
> > > github to ask questions. The familiarity of git will only come with
> more
> > > practice.
> > >
> > > Demos For Today's Class (8/19):
> > > @carolc <https://github.com/carolc> @ellatronic
> > > <https://github.com/ellatronic> @nmrosendin
> > > <https://github.com/nmrosendin> @SofyaMulenok
> > > <https://github.com/SofyaMulenok> - Please come prepared to talk about
> > > this week's assignment and how you completed it, and any remaining
> > > questions that you may have. Max of 2mins. The purpose of the demo or
> the
> > > assignment is not completeness or correctness. Just a review of steps
> > > taken, any problems encounters, and/or lessons learnt.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hackbrightacademy/pt-frontend-fall-2015/issues/8>.
> > >
> >
> >
> >
> > --
> > *Demi Skipper*
> > Architect
> > Penney Design Group
> > Demiskipper@gmail.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackbrightacademy/pt-frontend-fall-2015/issues/8#issuecomment-133050292>
> .
>



-- 
*Demi Skipper*
Architect
Penney Design Group
Demiskipper@gmail.com

**Comment by DiyahM** [comment]
Most developers break up changes into 'features' and push these features back to master and deploy them.

For the purposes of this class, you can push to master and deploy as much as possible. No need to create another repo. Use your existing repo and push to that, and don't forget to deploy using Github Pages.
