### ISSUE TITLE
Group Project Idea: Data Visualizations and Other Fun Stuff with Diversity Stats

### ISSUE THREAD

**Issue by SoItGoes33** [hackbrightacademy/pt-frontend-fall-2015#9]
Hello -

I didn't really like my own pitch so I was wondering if anyone else was interested in the idea that Diyah mentioned? Her idea was to create some data visualizations (and any other ideas that the group may have) using the diversity stats that Tracy from Pinterest has been collecting.  Here is a link to a Nov 2014 article that I think gives pretty good background about Tracy Chou and what she's doing: http://www.vogue.com/4537369/pinterest-tracy-chou-silicon-valley/  (It is a Vogue article but still good, I think).

Anybody interested and want to form a group for this project?

**Comment by soumiafares** [comment]
Count me in! Would love to work on this :)

**Comment by carolc** [comment]
Yes!! I didn't really like mine either and wanted to do this one right when
she suggested it!

Carol

**Comment by DiyahM** [comment]
Hey Guys! Thanks for being proactive about picking a project and team. As this team now has 3 members, I'm going to close this thread.

Next steps:
1) One of you should create a repo under your own account and add team members as a collaborators.
2) Continue the discussion in the new repo using issues.
